development:
  adapter: mysql
  encoding: utf8
  database: zookuu_development
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock  
          
test:
  adapter: mysql
  encoding: utf8
  database: zookuu_test
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
  
production:
  adapter: mysql
  encoding: utf8
  database: yazookuu
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
